# This is an example of what your 1.6_webapp.yml playbook should look
# like after completing the tasks described in 1.10:

# - Install nginx, Redis, and supervisord via roles
# - Write a custom role to manage Flask with supervisord
# - Persist number of visits in Redis
# - Increment and display visits to user

# This is a role-based version of the playbook from 1.6_webapp.yml; if you
# run into issues completing section 1.8, you can use it as inspiration.

# This will deploy a web app locally rather than to another server.
- name: Deploy a web application
  hosts: control_machine

  # Values we're using in more than one place are best
  # stored as variables. Playbooks are one of the many
  # locations we can define variables.
  vars:
    deploy_directory: ~/apps
    nginx_listen_port: 80
    nginx_upstream_port: 5000

  # Roles are executed before tasks.
  roles:
    # This is a different Flask role that uses supervisor.
    - role: flask_supervisor_example
      tags: [flask]
      # Variables can be passed into a role
      flask_app: "flask-redis"
      flask_src: ../files/flask-redis/flask-redis.py
      flask_directory: "{{ deploy_directory|expanduser }}"
      flask_port: "{{nginx_upstream_port }}"

    - { role: nginx_example, tags: [nginx] }

    - { role: redis_example, tags: [redis] }

  tasks:
    # This is a great example of a task that doesn't belong in either
    # the Flask role or the Redis role, because it only matters to the
    # intersection of them.
    - name: Install flask-redis
      become: yes
      pip:
        name: flask-redis
      notify: restart flask

    # It's common to use a role to install 'basic' configuration (and
    # provide handlers), but then override that configuration in the
    # `tasks:` section of the role.
    - name: Template nginx configuration file
      become: yes
      template:
        src: ../templates/proxy.j2
        dest: /etc/nginx/sites-available/proxy
      # The nginx handler is available because we included the role.
      notify: reload nginx

    # Create a symlink in `/etc/nginx/sites-enabled` pointing to the
    # file we previously templated into `/etc/nginx/sites-available`.
    - name: Enable this site
      become: yes
      file:
        state: link
        src: /etc/nginx/sites-available/proxy
        dest: /etc/nginx/sites-enabled/proxy
      notify: reload nginx

  # Role handlers won't be executed until the end of the `tasks:`
  # section, so we need to move these into `post_tasks` instead.
  post_tasks:
    # Ansible commands process much faster than manual execution, so
    # it's possible that nginx won't have bound to port 80 before we
    # attempt to query the server.
    - name: Wait for nginx to listen on port {{nginx_listen_port}}
      wait_for:
        port: "{{nginx_listen_port}}"
        # wait_for starts immediately and polls every second, but if
        # nginx hasn't started in 10 seconds, something is wrong.
        timeout: 10

    # The `uri` module is a basic HTTP client that is primarily for
    # checking status codes, but can also save response bodies.
    - name: Ensure that the proxy is functioning
      uri:
        url: http://localhost:{{nginx_listen_port}}
        return_content: yes
      # `register` saves the output to an Ansible variable.
      register: proxy_response
      # Mark the task as failed, but run the next task.
      failed_when: "'Deploying Applications With Ansible' not in proxy_response.content"
      ignore_errors: true

    # The `fail` module will stop a playbook with an error. The `when`
    # section will prevent the `fail` module from executing if the
    # condition evaluates to true. 
    - name: Make sure we're in the right class!
      debug:
        msg: "Application {% if proxy_response.failed %}failed to deploy.{% else %}successfully deployed!{% endif %}"
      failed_when: proxy_response.failed
