# How to build a custom module in Ansible: http://docs.ansible.com/ansible/dev_guide/developing_modules_general.html

- hosts: localhost
  roles:
    # Custom modules embedded in roles become available after that
    # role has been loaded.
    - custom_role
  tasks:
    - name: Call my custom module
      # Or: create a file like custom_ruby_module.rb, custom_node_module.js, etc.
      custom_python_module:
        arg1: foo
        arg2: bar
      register: custom_module_output

    - name: Print custom module output
      debug: var=custom_module_output